### ISSUE TITLE
HumioCluster CRD Validation Error: podDisruptionBudget field validation issue

### ISSUE THREAD

**Issue by JacobValdemar** [humio/humio-operator#1000]
## Problem Description

When applying a HumioCluster resource with `podDisruptionBudget` configuration, the dry-run validation fails with the following error:

```
HumioCluster/logging/humio dry-run failed, reason: Invalid: HumioCluster.core.humio.com "humio" is invalid: spec.nodePools[0].spec.podDisruptionBudget: Invalid value: "object": no such key: maxUnavailable evaluating rule: At most one of minAvailable or maxUnavailable can be specified
```

## Root Cause

The issue is in the CRD validation rule for the `podDisruptionBudget` field. The [current validation rule](https://github.com/humio/humio-operator/blob/operator-0.29.2/config/crd/bases/core.humio.com_humioclusters.yaml#L11957-L11961) is:

```yaml
x-kubernetes-validations:
- message: At most one of minAvailable or maxUnavailable can be specified
  rule: self.minAvailable == null || self.maxUnavailable == null
```

This rule incorrectly checks for `null` values instead of field existence. When only `minAvailable` is specified in the configuration, the `maxUnavailable` field doesn't exist in the object, making `self.maxUnavailable` undefined rather than null.

## Reproduction Steps

1. Create a HumioCluster resource with the following `podDisruptionBudget` configuration:
```yaml
podDisruptionBudget:
  enabled: true
  minAvailable: 4
```

2. Apply the resource with dry-run validation
3. Observe the validation error

## Expected Behavior

The validation should pass when only one of `minAvailable` or `maxUnavailable` is specified, as intended by the validation rule.

## Current Workarounds

1. **Remove podDisruptionBudget**: Remove the entire `podDisruptionBudget` configuration in HumioCluster and create your own PDB.

## Proposed Fix

The validation rule should be updated to check for field existence rather than null values:

```yaml
x-kubernetes-validations:
- message: At most one of minAvailable or maxUnavailable can be specified
  rule: !has(self, 'minAvailable') || !has(self, 'maxUnavailable')
```

Or something else. I am not an expert in CRDs :-)

## Environment

- Humio Operator Version: 0.29.2
- Kubernetes Version: Any version supporting CRD validation rules
- CRD File: [config/crd/bases/core.humio.com_humioclusters.yaml](https://github.com/humio/humio-operator/blob/master/config/crd/bases/core.humio.com_humioclusters.yaml)

## Impact

This validation error prevents users from applying HumioCluster resources with valid `podDisruptionBudget` configurations, forcing them to use workarounds or remove the configuration entirely.
