### ISSUE TITLE
Add support for legacy RBAC - view-group-permissions.json

### ISSUE THREAD

**Issue by schofield** [humio/humio-operator#158]
Some users still rely on the older RBAC implementation via JSON. Add support to the operator for starting Humio pods with a configmap that uses extraVolumes and extraVolumeMounts, similar to the extraKafkaConfigs option.

**Comment by nevosial** [comment]
Create a configMap with your rbac file and then use the extraHumioVolumeMounts in the cluster specs. 
```
....
  extraHumioVolumeMounts:
    - name: role-permissions
      mountPath: /app/humio/humio-data/role-permissions.json
      subPath: role-permissions.json
      readOnly: true
  extraVolumes:
    - name: role-permissions
      configMap:
        name: humio-rbac
....
```
