### ISSUE TITLE
Add humio to linkerd service mesh

### ISSUE THREAD

**Issue by kaspernissen** [humio/humio-operator#204]
We are currently trying to setup humio with humio-operator in a centralized logging cluster. The idea is to use linkerd multicluster to create the network mesh between the logging cluster and other clusters. The specific use case in the first place is to only create a mesh between humio in the centralized cluster with fluent-bit running as a `DaemonSet` in another cluster. 

The first step in this process is to have humio running in the service mesh. Unfortunately, we are running into some issues. As far as I understand the humio-operator creates service accounts for each container running in the pod. Linkerd uses Kubernetes ServiceAccounts to define service identity. (https://linkerd.io/2/tasks/securing-your-service/)

As seen in the error output below, `linkerd` seems to be mounting the wrong token, namely the auth token instead of the humio token, which results in a mismatch. More information on how mutual TLS works in linkerd can be found here: https://linkerd.io/2/features/automatic-mtls/#how-does-it-work

I'm not sure whether this is a humio-operator problem or linkerd problem. Anyhow, we would like to get some pointers to how we can move forward with this. One option could be to disable identity in the proxy and let humio handle this instead, but it would be nice if we could leave the mutual tls part to the mesh instead. I've also asked this question in the linkerd community slack.

Further as seen in the below steps, it would be nice to be able to add annotations to pods for the humio-operator, so that we can enable and configure the proxies for the humio-core pods instead of the entire namespace. I've commented on the newly created issue as well: https://github.com/humio/humio-operator/issues/203 
 
## Steps to reproduce

1. Spin up Humio-operator in kind:
```
$ ./hack/test-helm-chart-kind.sh
```

2. Install linkerd stable-2.8.1
```
$ linkerd install | kubectl apply -f -
```

3. Verify linkerd is running
```
$ linkerd check
```

4. Edit default namespace
```
$ kubectl edit ns default
``` 

5. Add annotation: 
```
  annotations:
    linkerd.io/inject: enabled
```

6. Delete humio-core pod
```
$ kubectl delete pod example-humiocluster-core-XXXXXXX
```

7. Read the logs of the linkerd-proxy
```
$ kubectl logs -f example-humiocluster-core-XXXXXXX -c linkerd-proxy
```

Error:
```\
[    60.70596035s] ERROR daemon:identity: linkerd2_proxy_identity::certify: Failed to certify identity: grpc-status: FailedPrecondition, grpc-message: "requested identity did not match provided token: requested=example-humiocluster-humio.default.serviceaccount.identity.linkerd.cluster.local; found=example-humiocluster-auth.default.serviceaccount.identity.linkerd.cluster.local"
```

**Comment by jswoods** [comment]
I haven't spent much time looking into the linkerd part yet, but to get past this issue, you could possibly create your own service account and then set `humioServiceAccountName` and `authServiceAccountName` to use that service account so they're the same.

E.g. if you create a service account called "my-service-account" and then in the HumioCluster spec have:
```
spec:
  humioServiceAccountName: my-service-account
  authServiceAccountName: my-service-account
```
And then in theory linkerd would request `my-service-account.default.serviceaccount.identity.linkerd.cluster.local`.

Though this is not ideal from a security perspective if using IRSA since then the auth container would have the same IAM access as the humio container.

**Comment by jswoods** [comment]
Looking at the linkerd code here https://github.com/linkerd/linkerd2/blob/c5d3b281bee75935870b209c75fa28a6f87dcd02/pkg/inject/inject.go#L598, it looks to me like they grab the serviceaccount attached to the first container in the pod. In our case that is the auth container. So I do think this deserves an issue or PR against the linkerd project, perhaps where you can optionally specify the name of the container from which to inherit the serviceaccount. Until then the only options I can come up with is the solution above or re-ordering the containers in the pod, but that seems quite hacky.

**Comment by kaspernissen** [comment]
Thank you for the ideas and suggestions, @jswoods! 

I will create an issue against the linkerd project as well. I've already reached out through their Slack community, but will also create a PR.

I tried your suggestion, but it doesn't seem to work as it looks like you leave out the creation of necessary resources to the user, when specifying the `authServiceAccountName`.  I created a simple `ServiceAccount`:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: humio
  namespace: default
```
Updated the `HumioCluster` resource with the following: 
```
spec:
  humioServiceAccountName: humio
  authServiceAccountName: humio
```
This fails with the error: 
```
  Warning  FailedMount  1s (x5 over 9s)  kubelet, kind-control-plane  MountVolume.SetUp failed for volume "auth-service-account-secret" : secret "humio" not found
```
Which is what is happening here, you just use the `authServiceAccountName` as the secret, but this is not being created. https://github.com/humio/humio-operator/blob/03badb6f647f9fecdc8db0a63efccb8ea513e047/controllers/humiocluster_controller.go#L1331 

The `RoleBinding` should probably also be updated manually to bind to the newly created `ServiceAccount`?

Could you provide some more guidance on how to proceed?

**Comment by kaspernissen** [comment]
I see you already have an open issue on providing docs for this. I'm a bit unsure on how to use this feature. https://github.com/humio/humio-operator/issues/163

**Comment by kaspernissen** [comment]
I found this comment and your reasoning for the solution of multiple service accounts. 
https://github.com/humio/humio-operator/blob/03badb6f647f9fecdc8db0a63efccb8ea513e047/controllers/humiocluster_controller.go#L546

After reading the linked comment on kubernetes, I understand the reasoning for wanting to do this, but reading the public decision it doesn't sound like something that will be "officially" be supported in the near future and the current solution is a bit of a hack?

**Comment by kaspernissen** [comment]
I finally managed to get this working and we now have linkerd-proxy injected in the pod with the correct identity and receiving ingest from a cluster on the other side of mesh. 🚀 

For reference, here's what I did: 

As @jswoods suggested, I've set the following in the `HumioCluster` spec: 
```
spec:
  humioServiceAccountName: humio
  initServiceAccountName: humio
  authServiceAccountName: humio
```
This requires a few resources to be created and managed manually on the side of the operator. 
- ServiceAccount
- ServiceAccountSecret
- ClusterRole
- ClusterRoleBinding
- Role
- RoleBinding

```
apiVersion: v1
kind: Secret
metadata:
  name: humio
  namespace: logging
  annotations:
   kubernetes.io/service-account.name: humio
type: "kubernetes.io/service-account-token"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: humio
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humio
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: humio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: humio
subjects:
- kind: ServiceAccount
  name: humio
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: humio
  namespace: logging
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: humio
  namespace: logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: humio
subjects:
- kind: ServiceAccount
  name: humio
  namespace: logging
```

As we now have mTLS from the mesh, we have further disabled TLS in humio.
