### ISSUE TITLE
Fetch Kafka/Zookeeper endpoints from MSK

### ISSUE THREAD

**Issue by estahn** [humio/humio-operator#209]
It would be great to see the operator fetch the Kafka/Zookeeper endpoints from AWS directly, possibly like this:

```yaml
apiVersion: core.humio.com/v1alpha1
kind: HumioCluster
metadata:
  name: humio
spec:
  kafka:
    msk:
      enabled: true
      region: ap-southeast-2
      clusterName: humio
```

This would possibly remove the need for
```yaml
  extraKafkaConfigs: "security.protocol=SSL"
  tls:
    enabled: true
```
and hand-coding the endpoints:
```
    - name: "ZOOKEEPER_URL"
      value: "z-2.humio.xxx.c3.kafka.ap-southeast-2.amazonaws.com:2181,z-3.humio.xxx.c3.kafka.ap-southeast-2.amazonaws.com:2181,z-1.humio.xxx.c3.kafka.ap-southeast-2.amazonaws.com:2181"
    - name: "KAFKA_SERVERS"
      value: "b-3.humio.xxx.c3.kafka.ap-southeast-2.amazonaws.com:9094,b-2.humio.xxx.c3.kafka.ap-southeast-
```
