### ISSUE TITLE
Renaming repository/ingesttoken/parser not working

### ISSUE THREAD

**Issue by estahn** [humio/humio-operator#214]
Instead of renaming the repository, it creates a new repository and possibly leaves the prior one abandoned (in terms of management).

Steps to reproduce:

1. Create repository:
```
apiVersion: core.humio.com/v1alpha1
kind: HumioRepository
metadata:
  name: myrepo
spec:
  managedClusterName: humio
  name: myrepo
  description: "foobar"
```

2. Rename repository
```
apiVersion: core.humio.com/v1alpha1
kind: HumioRepository
metadata:
  name: myrepo
spec:
  managedClusterName: humio
  name: myrepo123
  description: "foobar"
```

Note `.metadata.name` is the same, so the operator should reconcile and detect the name change.
