### ISSUE TITLE
Support for ServiceMonitor

### ISSUE THREAD

**Issue by SaaldjorMike** [humio/humio-operator#219]
- [x] For the operator itself. The operator-sdk scaffolding already created one file which contains a ServiceMonitor object. We would need to update the operator itself so we can use it, and then include the ServiceMonitor in our Helm chart which can be enabled when installing the operator. Fixed by https://github.com/humio/humio-operator/pull/242.
- [ ] For Humio pods. It might be fine to assume a user would want to use ServiceMonitor for Humio pods if they are enabling it for the operator itself. Add `PROMETHEUS_METRICS_PORT` to environment variables for HumioCluster pods, then set up the Service and ServiceMonitor objects pointing to it. If TLS is configured for Humio, the metrics port will also require TLS. [ServiceMonitor.Spec.Endpoints](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#endpoint) contain a [TLSConfig](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#tlsconfig) which allows us to load the custom CA when TLS is enabled.

**Comment by hagzag** [comment]
I have the following for the operator:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: humio-operator-metrics
  namespace: logging
  labels:
    app.kubernetes.io/instance: humio-operator-metrics
    app.kubernetes.io/name: humio-operator-metrics
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: humio
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: humio-oprtator-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: humio-operator-metrics
  endpoints:
  - port: metrics
    path: /metrics
  namespaceSelector:
    matchNames:
    - logging
  ```
And the following for humioc-cluster:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: humio-quickstart-metrics
  namespace: logging
  labels:
    app.kubernetes.io/instance: humio-quickstart-metrics
    app.kubernetes.io/name: humio
spec:
  ports:
  - name: metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: humio-quickstart
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: humio-quickstart-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: humio-quickstart-metrics
  endpoints:
  - port: metrics
    path: /metrics
  namespaceSelector:
    matchNames:
    - logging
```
