### ISSUE TITLE
HumioCluster should have license attribute

### ISSUE THREAD

**Issue by estahn** [humio/humio-operator#238]
I would like to be able to define the license via `HumioCluster`, e.g.

```yaml
apiVersion: core.humio.com/v1alpha1
kind: HumioCluster
metadata:
  name: humio
  namespace: logging
spec:
  image: "humio/humio-core:1.16.0"
  license: "abce..."
```
or/and
```yaml
apiVersion: core.humio.com/v1alpha1
kind: HumioCluster
metadata:
  name: humio
  namespace: logging
spec:
  image: "humio/humio-core:1.16.0"
  license:
    secretKeyRef:
      name: humio-license
      key: data
```
