### ISSUE TITLE
Ingress Address Conflict Issue

### ISSUE THREAD

**Issue by zach-robinson** [humio/humio-operator#334]
Created a Humio cluster with these settings:

```
spec:
  environmentVariables:
  - name: PUBLIC_URL
    valueFrom:
      secretKeyRef:
        key: TRUSTED_URI_PREFIX_2
        name: cphumio-cloudpakhumiocluster-oidc
  helperImage: humio/humio-operator-helper:0.0.8
  image: humio/humio-core:1.18.1
  ingress:
    annotations:
      kubernetes.io/ingress.class: ibm-icp-management
    controller: nginx
    enabled: true
    tls: false
  path: /humio
```

This results in a conflict where `cphumio-cloudpakhumiocluster-es-ingest` and `cphumio-cloudpakhumiocluster-general` both point to the same path: 

```
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: cphumio-cloudpakhumiocluster
          servicePort: 9200
        path: /humio
        pathType: ImplementationSpecific
```
```
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: cphumio-cloudpakhumiocluster
          servicePort: 8080
        path: /humio
        pathType: ImplementationSpecific
```

This results in only one of these endpoints getting served by Nginx depending on the order in which the ingresses were reconciled.
