### ISSUE TITLE
Resource requirements

### ISSUE THREAD

**Issue by estahn** [humio/humio-operator#339]
The operator OOMs with these resources. Should be heaps:

```
      operator:
        resources:
          limits:
            cpu: 250m
            memory: 400Mi
          requests:
            cpu: 250m
            memory: 400Mi
```
