### ISSUE TITLE
Describing humio action leaks secret value

### ISSUE THREAD

**Issue by hoeg** [humio/humio-operator#479]
Hi team,

when creating a `core.humio.com/v1alpha1` resource with a `secretKeyRef` e.g.

```
apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: "slack-alerts"
spec:
  managedClusterName: humio
  name: "slack-alerts"
  viewName: "services"
  slackPostMessageProperties:
    apiTokenSource:
      secretKeyRef:
        name: slack-secret
        key: slack.token
    channels:
      - "#alerts"
    fields:
      Environment: "{field:environment}"
      Logs: "{events_str}"
```

the value of the `slack-secret` is printed when doing `kubectl describe humioactions.core.humio.com slack-alerts`. Here is a sample output of running describe:

```
...
Spec:
  Managed Cluster Name:  humio
  Name:                  slack-alerts
  Slack Post Message Properties:
    API Token:  <actual value of slack.token>
    API Token Source:
      Secret Key Ref:
        Key:   slack.token
        Name:  slack.token
    Channels:
      #alerts
    Fields:
      Environment:  {field:environment}
      Logs:         {events_str}
  View Name:        services
Status:
  State:  Exists
Events:   <none>
```

I would expect this secret not to be printed. Is this intended behaviour? If not, I wouldn't mind taking a stab at it myself if that is ok?

**Comment by SaaldjorMike** [comment]
Completely agree that it shouldn't show the secret value when describing a `HumioAction` resource. Feel free to take a stab at it.

**Comment by hoeg** [comment]
As there are ongoing development on this repo may I suggest that we create a security advisory for this? I see that there is a fix in the works so it would be great to notify users about this so they can upgrade when time comes.

**Comment by fanicia** [comment]
As a follow-up to this, I had a chat with @hoeg offline and he pointed out that while this issue might seem like a "minor" thing, as the operator is "only" potentially leaking things like Slack or PagerDuty tokens, consider what happens if you make an action that looks like this:


```yaml
piVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: "slack-alerts"
spec:
  managedClusterName: humio
  name: "slack-alerts"
  viewName: "services"
  slackPostMessageProperties:
    apiTokenSource:
      secretKeyRef:
        name: prod-aws-key
        key: aws.secret.access.key
    channels:
      - "#alerts"
    fields:
      Environment: "{field:environment}"
      Logs: "{events_str}"
```

If you are able to deploy this action, you can then describe the resulting action and it would leak the corresponding aws secret key even if their Kubernetes credentials don't allow them to read the secret. All in all, I can imagine scenarios where this could actually be a considerable issue, depending on people's processes around deploying these resources to their environments 🙂
