### ISSUE TITLE
HumioAction finalizer depends on HumioView

### ISSUE THREAD

**Issue by Crevil** [humio/humio-operator#505]
If a view is deleted prior to an action pointing to that view, the action can never be reconciled and thus ther termination is stuck.

Reconciliation error:

```json
{
  "level": "error",
  "ts": "2021-11-30T18:47:39.910335719Z",
  "caller": "controllers/humioaction_controller.go:101",
  "func": "github.com/humio/humio-operator/controllers.(*HumioActionReconciler).Reconcile",
  "msg": "got unexpected error when checking if action exists",
  "Operator.Commit": "716bb207b4d2a4305e198e1978c4100f600a787a",
  "Operator.Date": "2021-11-09T21:43:02+00:00",
  "Operator.Version": "0.13.0",
  "Request.Namespace": "logging",
  "Request.Name": "slack-name",
  "Request.Type": "HumioActionReconciler",
  "Reconcile.ID": "rwmwfy",
  "error": "problem getting view for action #squad-calipso-alerts: view <name> does not exist",
  "stacktrace": "github.com/humio/humio-operator/controllers.(*HumioActionReconciler).Reconcile\n\t/workspace/controllers/humioaction_controller.go:101\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214"
}
```

## Replication

Apply below resources and then delete the view, wait for reconciliation and then delete action.
The action is now stuck with above error.

```yaml
apiVersion: core.humio.com/v1alpha1
kind: HumioView
metadata:
  name: name
  namespace: logging
spec:
  managedClusterName: humio
  name: name
  connections:
    - repositoryName: repo
      filter: "*"
---
apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: name
  namespace: logging
spec:
  managedClusterName: humio
  name: name
  viewName: name
  slackPostMessageProperties:
    apiTokenSource:
      secretKeyRef:
        name: humio
        key: slack.token
    channels:
      - "#channel"
    fields:
      Logs: "{events_str}"
```
