### ISSUE TITLE
Evicted pods are not replaced

### ISSUE THREAD

**Issue by bchess** [humio/humio-operator#512]
Humio pods can get evicted for using too much local storage. The Pod goes into phase `Failed`. If this pod were managed with a Deployment or StatefulSet controllers, it'd be replaced with a new pod. However, humio-operator does not.

pod.status copied below just for reference:
```
status:
  message: 'Pod ephemeral local storage usage exceeds the total limit of containers
    <X>Gi. '
  phase: Failed
  reason: Evicted
  startTime: "2021-12-10T17:10:08Z"
```
