### ISSUE TITLE
Cannot provide multiple query strings for the same repo with `HumioView` CR

### ISSUE THREAD

**Issue by bderrly** [humio/humio-operator#745]
Due to an issue with the https://github.com/humio/cli API for updating views, it is currently not possibly to do something like this in a `HumioView` CR:

```yaml
apiVersion: core.humio.com/v1alpha1
kind: HumioView
spec:
  connections:
  - filter: |
      somestring
    repositoryName: repoOne
  - filter: |
      otherstring
    repositoryName: repoOne
  - filter: |
        astring
    repositoryName: repoTwo
  name: mySpecialView
```

The API will currently only pass the last mention of repoOne on to the GraphQL mutation. I created https://github.com/humio/cli/pull/138 to address the issue of the humio client. Once the client has been updated then humio-operator can utilize the new parameter which is `map[string][]string` rather than `map[string]string`.
