### ISSUE TITLE
Missing Tolerations in `HumioBootstrapToken` Pod

### ISSUE THREAD

**Issue by beharc** [humio/humio-operator#963]
### Context

When deploying a `HumioCluster` using the Humio Operator (`v0.28.2`) on a Kubernetes cluster with dedicated node pools. To control pod scheduling, I'm applying `affinity` and `tolerations` in the `HumioCluster` spec, targeting nodes with specific roles and storage.

However, I've encountered an issue where the automatically generated bootstrap token pod (`HumioBootstrapToken`) does **not** inherit the tolerations from the parent `HumioCluster` resource. As a result, the pod cannot be scheduled and remains in a pending state indefinitely.

### `HumioCluster` Spec (Simplified)

```yaml
apiVersion: core.humio.com/v1alpha1
kind: HumioCluster
metadata:
  name: non-prod
  namespace: humio-system
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values: [amd64]
              - key: k8s-app
                operator: In
                values: [humio]
  tolerations:
    - key: k8s-app
      operator: Equal
      value: humio
      effect: NoSchedule
    - key: storage-class
      operator: Equal
      value: nvme-local
      effect: NoSchedule
  image: humio/humio-core:1.181.0
  dataVolumePersistentVolumeClaimSpecTemplate:
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 1500Gi
    storageClassName: nvme-local
  license:
    secretKeyRef:
      name: humio-cluster-license
      key: data
```

### Actual Behavior

The generated bootstrap token pod is created with the correct node affinity, but **missing** the `k8s-app` and `storage-class` tolerations, resulting in it not matching any schedulable node in our cluster:

```yaml
kind: Pod
metadata:
  name: non-prod-bootstrap-token-onetime
  namespace: humio-system
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values: [amd64]
              - key: k8s-app
                operator: In
                values: [humio]
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
```

###  Expected Behavior

The `HumioBootstrapToken` pod should inherit tolerations defined in the parent `HumioCluster` resource. This would ensure the pod can be scheduled to appropriate nodes during cluster bootstrap.

### Current Workaround

To unblock scheduling, you can patch the bootstrap token or avoid using affinities.

```bash
kubectl patch humiobootstraptoken non-prod -n humio-system --type merge -p '{"spec":{"affinity":{}}}'
```
